#!/bin/bash
. base

srcShared=src/shared/module/module.ts
targetShared="$ProjectPath/view/shared/module/$entity-search.module.ts"
echo "copying search module template to $targetShared"
cp $srcShared $targetShared
replace $targetShared

dirs=src/view/*
for d in $dirs
do
  dname=$(basename $d)
  echo $dname
  files=`realpath "./src/view/$dname/*"`
  for f in $files
  do
    action="$entity-$dname"
    srcFileName=$(basename $f)
    srcFilePath=`realpath "./src/view/$dname/$srcFileName"`
    targetPath="$ProjectPath/view/$entity/$action/$action.$srcFileName"
    echo "copying template $srcFilePath to $targetPath"
    cp $srcFilePath $targetPath
    echo "patching view files for $targetPath"
    replace $targetPath
  done
done
