#!/bin/bash
. base

cp -p src/*.ts tmp/
replace tmp/*

# copy modified source files to target directories
files=tmp/*.ts
for f in $files
do
  path="$ProjectPath/$(basename $f .ts)/${entity}.ts"
  cp -p $f $path
done

# modify target files-to-patch in place
files=(
  "$ProjectPath/dao/dao-repository.ts"
  "$ProjectPath/store/store-repository.ts"
  "$ProjectPath/app.module.ts"
  "$ProjectPath/reducer/index.ts"
)
echo "patching model dependent source files in target project"
for f in ${files[@]}
do
  echo $f
  # duplicates codegen line(s) in target src file for sed replace task
  sed -i -n 'p; s/\/\/codegen|//p' $f
  replace $f
done
echo "done"
